### ISSUE TITLE
Documentation missing from PyPI tarball

### ISSUE THREAD

**Issue by vext01** [takluyver/terminado#22]
Hi,

Not sure if this was intentional, but the `doc` directory is missing from the PyPI tarball for terminado-0.5. This is present in git under the 0.5 tag. Was it removed on purpose?

I'm packaging terminado for OpenBSD and I would package the docs if they were present in the release tarball.

Cheers

**Comment by takluyver** [comment]
It wasn't removed on purpose - files have to be explicitly included in PyPI tarballs by instructions in [MANIFEST.in](https://github.com/takluyver/terminado/blob/master/MANIFEST.in). More info about the format here: https://docs.python.org/2/distutils/sourcedist.html#the-manifest-in-template

Part of me feels that packagers should get the source tarballs from git tags (which Github makes [easy](https://github.com/takluyver/terminado/archive/0.5.tar.gz)) rather than PyPI tarballs. But I don't feel strongly about this, so if you want to make a PR to add the docs to the PyPI tarball, go for it.

**Comment by takluyver** [comment]
With 0.7, the docs (source) are now in the tarball.
