### ISSUE TITLE
Does it Work on Windows  ? Otherwise any hope or alternative ?

### ISSUE THREAD

**Issue by stonebig** [takluyver/terminado#7]

**Comment by takluyver** [comment]
It does not. I plan to investigate whether it's possible to do something with git bash, but I'm not terribly optimistic. Pseudoterminals are a pretty low level feature of Unix systems, and I don't know of anything equivalent in Windows.

**Comment by takluyver** [comment]
Actually, it looks like it may be possible simply by piping text to and from git bash. There will probably be some limitations.

**Comment by stonebig** [comment]
Any incremental improvement would be nice for Windows users.
Maybe should you target only python3.3+ if it can help reaching a solution.

**Comment by takluyver** [comment]
I'm working on it. The limitations will probably be things like terminal resizing not working. If it works, it should be straightforward to make it work on the same versions of Python that terminado already supports (2.7, 3.3+).

**Comment by takluyver** [comment]
There's a branch [here](https://github.com/takluyver/terminado/compare/windows) with git bash very roughly working.

![screenshot from 2015-02-24 16 46 50](https://cloud.githubusercontent.com/assets/327925/6362968/597d1b2e-bc47-11e4-807b-fc4167f3b754.png)

Problems I'm aware of:
- Subprocesses like Python do not realise they're in a terminal, so they behave as if they were in a pipe. Even using `python -i`, I can't interact with it. `python -c "print(123)"` works fine, though.
- Shortcuts like Ctrl-C don't work. That's expected - on a Unixy system it's the pty that would handle turning Ctrl-C into SIGINT, and that's what we're missing here. Signals in general are not a Windows thing, so I'm not sure how best to handle this.
- Speed: there's a brief but noticeable pause before drawing the next prompt.
- Terminal size: I don't know of any way to update it. Then again, that's not such a big issue, because:
- Full screen programs like vim show nothing, but lock up the terminal. Something must be translating the curses calls into equivalent Windows API calls, but I don't know where that's happening.
- Programs that take control of the full terminal, like vim, do not show up

**Comment by takluyver** [comment]
This library and exe might be useful if someone has the will to take this further: https://github.com/rprichard/winpty

**Comment by stonebig** [comment]
`winpty` is not on pypi.
I don't find where you or MinRK already said that `https://pypi.python.org/pypi/prompt_toolkit` was not a good solution either.
==> Droping the request for 'was a disproportionate effort in 2015 to get it right'.

**Comment by takluyver** [comment]
winpty is not a Python package, it's a C++ thing. I'm not entirely sure how we would use it, but it appears to do what we'd want. The setup instructions are pretty complex, though, so I haven't pursued it.

prompt_toolkit is solving a different problem from this.

**Comment by stonebig** [comment]
a glimmer of hope ?

**Comment by takluyver** [comment]
Sorry, I don't plan to take this any further. I don't think I can make it
reliable enough to be worth supporting windows - I don't want to deal with
a steady stream of bug reports I can't resolve.

**Comment by stonebig** [comment]
no problem, better that than a painfull death

**Comment by stonebig** [comment]
I see terminado on jupyter-notebook (setup.py) extras for win32. Is it Working or dropped for this platform ?

**Comment by takluyver** [comment]
Still no windows support. I think it can be installed OK, so it's not a
problem for the notebook to specify it as a dependency on all platforms.
But it can't be imported on windows.

**Comment by stonebig** [comment]
someone just told me some problems may go away for `pymux` If I use cygwin. Would it also improve situation for terminado ?

**Comment by takluyver** [comment]
I don't know; feel free to experiment, but as we discussed in another thread, we don't generally recommend using Cygwin, and I don't intend to support it for Terminado. We find that it's better to use a full Unix environment (such as your favourite Linux distro) rather than trying to graft a Unix environment onto Windows.

**Comment by stonebig** [comment]
lonely feeling ... https://youtu.be/fhv-4QLGsso?t=1211
